# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twss}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben VandenBos"]
  s.date = %q{2010-08-12}
  s.description = %q{Pre-trained "That's What She Said" Bayes classifier.
      Given a string, returns true if it's a TWSS joke.  Pre-trained from
      Twitter #twss.  Let the twss mashups begin!}
  s.email = %q{bvandenbos@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "data/classifier",
     "data/non_twss.txt",
     "data/twss.txt",
     "lib/twss.rb",
     "lib/twss/engine.rb",
     "lib/twss/trainer.rb",
     "lib/twss/tweet_collector.rb",
     "script/collect_non_twss.rb",
     "script/collect_twss.rb",
     "script/train.rb",
     "twss.gemspec"
  ]
  s.homepage = %q{http://github.com/bvandenbos/twss}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Pre-trained That's What She Said classifier}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<classifier>, [">= 1.3.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<twitter>, [">= 0"])
    else
      s.add_dependency(%q<classifier>, [">= 1.3.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<twitter>, [">= 0"])
    end
  else
    s.add_dependency(%q<classifier>, [">= 1.3.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<twitter>, [">= 0"])
  end
end

